# Generated by Django 4.2.7 on 2023-11-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0002_wordbank_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='wordbank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='jotter.wordbank'),
        ),
        migrations.AlterField(
            model_name='wordbank',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordbanks', to='jotter.context'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jotter.context')),
            ],
        ),
    ]
