# Generated by Django 4.2.7 on 2023-11-18 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jotter', '0003_alter_word_wordbank_alter_wordbank_context_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='wordbank',
            new_name='word_bank',
        ),
        migrations.CreateModel(
            name='PupilClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_group', models.CharField(max_length=30)),
                ('access_key', models.UUIDField()),
                ('pupils', models.ManyToManyField(related_name='pupils', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='classes',
            field=models.ManyToManyField(to='jotter.pupilclass'),
        ),
    ]
