# Generated by Django 4.2.7 on 2023-11-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0004_rename_wordbank_word_word_bank_pupilclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='classes',
        ),
        migrations.AddField(
            model_name='pupilclass',
            name='contexts',
            field=models.ManyToManyField(blank=True, to='jotter.context'),
        ),
        migrations.AlterField(
            model_name='image',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jotter.context'),
        ),
    ]
