# Generated by Django 4.2.7 on 2023-11-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0005_remove_context_classes_pupilclass_contexts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='classes',
            field=models.ManyToManyField(blank=True, to='jotter.pupilclass'),
        ),
    ]
