# Generated by Django 4.2.7 on 2023-11-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0006_context_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='classes',
        ),
        migrations.DeleteModel(
            name='PupilClass',
        ),
    ]
