# Generated by Django 4.2.7 on 2023-11-19 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jotter', '0007_remove_context_classes_delete_pupilclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='PupilClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_group', models.CharField(max_length=30)),
                ('access_key', models.UUIDField()),
                ('contexts', models.ManyToManyField(blank=True, related_name='assigned_classes', to='jotter.context')),
                ('pupils', models.ManyToManyField(related_name='pupil_classes', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
