# Generated by Django 4.2.7 on 2023-11-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotter', '0008_pupilclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupilclass',
            name='access_key',
            field=models.CharField(max_length=8),
        ),
    ]
