# Generated by Django 4.2.7 on 2023-11-22 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jotter', '0010_alter_jotter_author_alter_jotter_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupilclass',
            name='pupils',
            field=models.ManyToManyField(blank=True, related_name='pupil_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
